## Nombre de la aplicacion
spring.application.name=IncaCore
spring.profiles.default=dev

## Postgres
server.port=${SERVER_PORT:8080}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.schema=incacore
spring.datasource.hikari.maximum-pool-size=${DB_POOL_MAX_SIZE:2}
spring.datasource.hikari.minimum-idle=${DB_POOL_MIN_IDLE:0}
spring.datasource.hikari.connection-timeout=${DB_POOL_CONNECTION_TIMEOUT_MS:30000}
spring.datasource.hikari.idle-timeout=${DB_POOL_IDLE_TIMEOUT_MS:300000}
spring.datasource.hikari.pool-name=${spring.application.name}-pool

## Hibernate / JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=incacore

## Flyway
spring.flyway.schemas=incacore
spring.flyway.default-schema=incacore
spring.flyway.create-schemas=true

## JWT (JSON Web Token)
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

## Swagger / OpenAPI - Documentacion
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

## CORS - Origenes permitidos para el frontend
web.cors.allowed-origins=${CORS_ALLOWED:http://localhost:*,https://incacore.cambers.lat}

## Resend email delivery
resend.api-key=${RESEND_APIKEY}
resend.email=${RESEND_EMAIL}

## Frontend URLs
frontend.baseUrl: ${FRONT_BASE_URL:http://localhost:3000}
frontend.verifyEmailUrl: ${VERIFYEMAIL_URL:/auth/veryfy-email}
frontend.resetPasswordUrl: ${RESETPASSWORD_URL:/auth/reset-password}
